### ISSUE TITLE
Module GraphQL.Client.AsGql was not found

### ISSUE THREAD

**Issue by tbm206** [OxfordAbstracts/purescript-graphql-client#149]
As the title says, when the schema is generated using `purescript-graphql-client`, the generated schema module has an import:

```purs
import GraphQL.Client.AsGql (AsGql)
```

When I try to compile this, I get:

```sh
  10  import GraphQL.Client.AsGql (AsGql)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  Module GraphQL.Client.AsGql was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.
```

---

There are other error too; e.g.

```sh
  7  import GraphQL.Client.Directive.Location (MUTATION, QUERY, SUBSCRIPTION)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  Module GraphQL.Client.Directive.Location was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.
```

Am I doing something wrong?

**Comment by tbm206** [comment]
I managed to solve the issue by using `spago`'s `extraPackages` and pointing to this repository:

```yaml
workspace:
  packageSet:
    registry: 65.0.0
  extraPackages:
    graphql-client:
      git: https://github.com/OxfordAbstracts/purescript-graphql-client.git
      ref: main
```
